<?xml version="1.0" encoding="utf-8"?><Database Name="IPEM2" Class="DataClassesdevistasDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;AttachDbFilename=&quot;C:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\IPEM2.mdf&quot;;Integrated Security=True;Connect Timeout=30;User Instance=True" SettingsObjectName="IPEM298.My.MySettings" SettingsPropertyName="notebook" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Vista_Docente_x_dia" Member="Vista_Docente_x_dia">
    <Type Name="Vista_Docente_x_dia">
      <Column Name="dia_semana" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="id_personal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="apelliido_pers" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="nombre_pers" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DNI_pers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="turno_textbox" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Vista_inasistencia_personal" Member="Vista_inasistencia_personal">
    <Type Name="Vista_inasistencia_personal">
      <Column Name="id_asistencia_doc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha_asistencia" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="estado_textbox" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="observacion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DNI_pers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre_pers" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="apelliido_pers" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="id_personal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre_materia" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="nombre_curso" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="numero" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="turno_textbox" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vista_calificaciones" Member="vista_calificaciones">
    <Type Name="vista_calificaciones">
      <Column Name="id_materia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="parcial1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaParcial1" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="parcial2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaParcial2" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="parcial3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaParcial3" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="parcial4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaParcial4" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="integrador1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaInteg1" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="promedioetapa1" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="parcial5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaParcial5" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="parcial6" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaParcial6" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="parcial7" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaParcial7" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="parcial8" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaParcial8" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="integrador2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaInteg2" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="promedioetapa2" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="parcial9" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaParcial9" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="parcial10" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaParcial10" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="parcial11" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaParcial11" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="parcial12" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaParcial12" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="integrador3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaInteg3" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="promedioetapa3" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="promedio_anual" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="coloquio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechacoloquio" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="examen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaexamen" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="calif_definitiva" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="condicion_textbox" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="nombre_materia" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="nombre_alu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="apellido_alu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DNI_alu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_alumno" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vista_alum_xcurso" Member="vista_alum_xcurso">
    <Type Name="vista_alum_xcurso">
      <Column Name="id_alumno" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre_alu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="apellido_alu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DNI_alu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="especialidad" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="nombre_curso" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="turno_textbox" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_inscripcion_alu" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Vista_inasistencia_alumno" Member="Vista_inasistencia_alumno">
    <Type Name="Vista_inasistencia_alumno">
      <Column Name="id_asistencia_alu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha_asistencia_alu" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="observacion_asis_alu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="estado_asistencia_alu" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="id_alumno" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre_alu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="apellido_alu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DNI_alu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vista_modulocurso" Member="vista_modulocurso">
    <Type Name="vista_modulocurso">
      <Column Name="nombre_curso" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="numero" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hora_inicio" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="hora_fin" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="id_modulo_x_curso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="turno_textbox" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="id_modulo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_curso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VistaProfxMateria" Member="VistaProfxMateria">
    <Type Name="VistaProfxMateria">
      <Column Name="cant_hs_catedra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_profesor_materia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_curso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre_curso" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="nombre_materia" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="id_personal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_materia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VistaEstCalifxAlu" Member="VistaEstCalifxAlu">
    <Type Name="VistaEstCalifxAlu">
      <Column Name="id_alumno" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nombre_curso" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="id_curso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="condicion_textbox" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VistaCalifxCurso" Member="VistaCalifxCurso">
    <Type Name="VistaCalifxCurso">
      <Column Name="id_alumno" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_curso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre_curso" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="calif_definitiva" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VistaPrueba" Member="VistaPrueba">
    <Type Name="VistaPrueba">
      <Column Name="id_alumno" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_materia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre_materia" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="condicion_textbox" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vista_horario_personal" Member="vista_horario_personal">
    <Type Name="vista_horario_personal">
      <Column Name="dia_semana" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="nombre_materia" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="nombre_curso" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="numero" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hora_inicio" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="hora_fin" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="id_horario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_personal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="turno_textbox" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="especialidad_textbox" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nombre_pers" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="apelliido_pers" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="inicio" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="final" Type="System.String" DbType="Char(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Vista_libreta" Member="Vista_libreta">
    <Type Name="Vista_libreta">
      <Column Name="id_materia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="parcial1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="parcial2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="parcial3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="parcial4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="integrador1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="promedioetapa1" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="parcial5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="parcial6" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="parcial7" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="parcial8" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="integrador2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="promedioetapa2" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="parcial9" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="parcial10" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="parcial11" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="parcial12" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="integrador3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="promedioetapa3" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="promedio_anual" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="coloquio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="examen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="calif_definitiva" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="condicion_textbox" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="nombre_materia" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="nombre_alu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="apellido_alu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DNI_alu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_alumno" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre_curso" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="turno_textbox" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="especialidad" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Vista_profesor_x_materia" Member="Vista_profesor_x_materia">
    <Type Name="Vista_profesor_x_materia">
      <Column Name="id_profesor_materia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="apelliido_pers" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="nombre_pers" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DNI_pers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre_materia" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="nombre_curso" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="puesto_pers" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Vista_Alumno2" Member="Vista_Alumno2">
    <Type Name="Vista_Alumno2">
      <Column Name="id_alumno_x_curso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_alumno" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_curso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="especialidad" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="Expr1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Expr4" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="nombre_alu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="apellido_alu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DNI_alu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre_curso" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Expr3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Expr6" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha_inscripcion_alu" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Vista_alumnos_no_asignados_curso" Member="Vista_alumnos_no_asignados_curso">
    <Type Name="Vista_alumnos_no_asignados_curso">
      <Column Name="id_alumno" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_alu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="apellido_alu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="domicilio" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DNI_alu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha_inscripcion_alu" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fecha_nac_alu" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="mail_alu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="nomb_ape_tutor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dni_tutor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="telefono_tutor" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="foto_alu" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>