'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="IPEM2")>  _
Partial Public Class DataClassesdevistasDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Definiciones de métodos de extensibilidad"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.IPEM298.My.MySettings.Default.notebook, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property Vista_Docente_x_dia() As System.Data.Linq.Table(Of Vista_Docente_x_dia)
		Get
			Return Me.GetTable(Of Vista_Docente_x_dia)
		End Get
	End Property
	
	Public ReadOnly Property Vista_inasistencia_personal() As System.Data.Linq.Table(Of Vista_inasistencia_personal)
		Get
			Return Me.GetTable(Of Vista_inasistencia_personal)
		End Get
	End Property
	
	Public ReadOnly Property vista_calificaciones() As System.Data.Linq.Table(Of vista_calificaciones)
		Get
			Return Me.GetTable(Of vista_calificaciones)
		End Get
	End Property
	
	Public ReadOnly Property vista_alum_xcurso() As System.Data.Linq.Table(Of vista_alum_xcurso)
		Get
			Return Me.GetTable(Of vista_alum_xcurso)
		End Get
	End Property
	
	Public ReadOnly Property Vista_inasistencia_alumno() As System.Data.Linq.Table(Of Vista_inasistencia_alumno)
		Get
			Return Me.GetTable(Of Vista_inasistencia_alumno)
		End Get
	End Property
	
	Public ReadOnly Property vista_modulocurso() As System.Data.Linq.Table(Of vista_modulocurso)
		Get
			Return Me.GetTable(Of vista_modulocurso)
		End Get
	End Property
	
	Public ReadOnly Property VistaProfxMateria() As System.Data.Linq.Table(Of VistaProfxMateria)
		Get
			Return Me.GetTable(Of VistaProfxMateria)
		End Get
	End Property
	
	Public ReadOnly Property VistaEstCalifxAlu() As System.Data.Linq.Table(Of VistaEstCalifxAlu)
		Get
			Return Me.GetTable(Of VistaEstCalifxAlu)
		End Get
	End Property
	
	Public ReadOnly Property VistaCalifxCurso() As System.Data.Linq.Table(Of VistaCalifxCurso)
		Get
			Return Me.GetTable(Of VistaCalifxCurso)
		End Get
	End Property
	
	Public ReadOnly Property VistaPrueba() As System.Data.Linq.Table(Of VistaPrueba)
		Get
			Return Me.GetTable(Of VistaPrueba)
		End Get
	End Property
	
	Public ReadOnly Property vista_horario_personal() As System.Data.Linq.Table(Of vista_horario_personal)
		Get
			Return Me.GetTable(Of vista_horario_personal)
		End Get
	End Property
	
	Public ReadOnly Property Vista_libreta() As System.Data.Linq.Table(Of Vista_libreta)
		Get
			Return Me.GetTable(Of Vista_libreta)
		End Get
	End Property
	
	Public ReadOnly Property Vista_profesor_x_materia() As System.Data.Linq.Table(Of Vista_profesor_x_materia)
		Get
			Return Me.GetTable(Of Vista_profesor_x_materia)
		End Get
	End Property
	
	Public ReadOnly Property Vista_Alumno2() As System.Data.Linq.Table(Of Vista_Alumno2)
		Get
			Return Me.GetTable(Of Vista_Alumno2)
		End Get
	End Property
	
	Public ReadOnly Property Vista_alumnos_no_asignados_curso() As System.Data.Linq.Table(Of Vista_alumnos_no_asignados_curso)
		Get
			Return Me.GetTable(Of Vista_alumnos_no_asignados_curso)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Vista_Docente_x_dia")>  _
Partial Public Class Vista_Docente_x_dia
	
	Private _dia_semana As String
	
	Private _id_personal As Integer
	
	Private _apelliido_pers As String
	
	Private _nombre_pers As String
	
	Private _DNI_pers As Integer
	
	Private _turno_textbox As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dia_semana", DbType:="VarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property dia_semana() As String
		Get
			Return Me._dia_semana
		End Get
		Set
			If (String.Equals(Me._dia_semana, value) = false) Then
				Me._dia_semana = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_personal", DbType:="Int NOT NULL")>  _
	Public Property id_personal() As Integer
		Get
			Return Me._id_personal
		End Get
		Set
			If ((Me._id_personal = value)  _
						= false) Then
				Me._id_personal = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_apelliido_pers", DbType:="NVarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property apelliido_pers() As String
		Get
			Return Me._apelliido_pers
		End Get
		Set
			If (String.Equals(Me._apelliido_pers, value) = false) Then
				Me._apelliido_pers = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_pers", DbType:="NVarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_pers() As String
		Get
			Return Me._nombre_pers
		End Get
		Set
			If (String.Equals(Me._nombre_pers, value) = false) Then
				Me._nombre_pers = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DNI_pers", DbType:="Int NOT NULL")>  _
	Public Property DNI_pers() As Integer
		Get
			Return Me._DNI_pers
		End Get
		Set
			If ((Me._DNI_pers = value)  _
						= false) Then
				Me._DNI_pers = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_turno_textbox", DbType:="NVarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property turno_textbox() As String
		Get
			Return Me._turno_textbox
		End Get
		Set
			If (String.Equals(Me._turno_textbox, value) = false) Then
				Me._turno_textbox = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Vista_inasistencia_personal")>  _
Partial Public Class Vista_inasistencia_personal
	
	Private _id_asistencia_doc As Integer
	
	Private _fecha_asistencia As Date
	
	Private _estado_textbox As String
	
	Private _observacion As String
	
	Private _DNI_pers As Integer
	
	Private _nombre_pers As String
	
	Private _apelliido_pers As String
	
	Private _id_personal As Integer
	
	Private _nombre_materia As String
	
	Private _nombre_curso As String
	
	Private _numero As Integer
	
	Private _turno_textbox As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_asistencia_doc", DbType:="Int NOT NULL")>  _
	Public Property id_asistencia_doc() As Integer
		Get
			Return Me._id_asistencia_doc
		End Get
		Set
			If ((Me._id_asistencia_doc = value)  _
						= false) Then
				Me._id_asistencia_doc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fecha_asistencia", DbType:="Date NOT NULL")>  _
	Public Property fecha_asistencia() As Date
		Get
			Return Me._fecha_asistencia
		End Get
		Set
			If ((Me._fecha_asistencia = value)  _
						= false) Then
				Me._fecha_asistencia = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_estado_textbox", DbType:="NVarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property estado_textbox() As String
		Get
			Return Me._estado_textbox
		End Get
		Set
			If (String.Equals(Me._estado_textbox, value) = false) Then
				Me._estado_textbox = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_observacion", DbType:="NVarChar(50)")>  _
	Public Property observacion() As String
		Get
			Return Me._observacion
		End Get
		Set
			If (String.Equals(Me._observacion, value) = false) Then
				Me._observacion = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DNI_pers", DbType:="Int NOT NULL")>  _
	Public Property DNI_pers() As Integer
		Get
			Return Me._DNI_pers
		End Get
		Set
			If ((Me._DNI_pers = value)  _
						= false) Then
				Me._DNI_pers = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_pers", DbType:="NVarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_pers() As String
		Get
			Return Me._nombre_pers
		End Get
		Set
			If (String.Equals(Me._nombre_pers, value) = false) Then
				Me._nombre_pers = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_apelliido_pers", DbType:="NVarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property apelliido_pers() As String
		Get
			Return Me._apelliido_pers
		End Get
		Set
			If (String.Equals(Me._apelliido_pers, value) = false) Then
				Me._apelliido_pers = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_personal", DbType:="Int NOT NULL")>  _
	Public Property id_personal() As Integer
		Get
			Return Me._id_personal
		End Get
		Set
			If ((Me._id_personal = value)  _
						= false) Then
				Me._id_personal = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_materia", DbType:="NVarChar(40) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_materia() As String
		Get
			Return Me._nombre_materia
		End Get
		Set
			If (String.Equals(Me._nombre_materia, value) = false) Then
				Me._nombre_materia = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_curso", DbType:="NVarChar(5) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_curso() As String
		Get
			Return Me._nombre_curso
		End Get
		Set
			If (String.Equals(Me._nombre_curso, value) = false) Then
				Me._nombre_curso = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_numero", DbType:="Int NOT NULL")>  _
	Public Property numero() As Integer
		Get
			Return Me._numero
		End Get
		Set
			If ((Me._numero = value)  _
						= false) Then
				Me._numero = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_turno_textbox", DbType:="NVarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property turno_textbox() As String
		Get
			Return Me._turno_textbox
		End Get
		Set
			If (String.Equals(Me._turno_textbox, value) = false) Then
				Me._turno_textbox = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.vista_calificaciones")>  _
Partial Public Class vista_calificaciones
	
	Private _id_materia As Integer
	
	Private _parcial1 As System.Nullable(Of Integer)
	
	Private _fechaParcial1 As System.Nullable(Of Date)
	
	Private _parcial2 As System.Nullable(Of Integer)
	
	Private _fechaParcial2 As System.Nullable(Of Date)
	
	Private _parcial3 As System.Nullable(Of Integer)
	
	Private _fechaParcial3 As System.Nullable(Of Date)
	
	Private _parcial4 As System.Nullable(Of Integer)
	
	Private _fechaParcial4 As System.Nullable(Of Date)
	
	Private _integrador1 As System.Nullable(Of Integer)
	
	Private _fechaInteg1 As System.Nullable(Of Date)
	
	Private _promedioetapa1 As System.Nullable(Of Decimal)
	
	Private _parcial5 As System.Nullable(Of Integer)
	
	Private _fechaParcial5 As System.Nullable(Of Date)
	
	Private _parcial6 As System.Nullable(Of Integer)
	
	Private _fechaParcial6 As System.Nullable(Of Date)
	
	Private _parcial7 As System.Nullable(Of Integer)
	
	Private _fechaParcial7 As System.Nullable(Of Date)
	
	Private _parcial8 As System.Nullable(Of Integer)
	
	Private _fechaParcial8 As System.Nullable(Of Date)
	
	Private _integrador2 As System.Nullable(Of Integer)
	
	Private _fechaInteg2 As System.Nullable(Of Date)
	
	Private _promedioetapa2 As System.Nullable(Of Decimal)
	
	Private _parcial9 As System.Nullable(Of Integer)
	
	Private _fechaParcial9 As System.Nullable(Of Date)
	
	Private _parcial10 As System.Nullable(Of Integer)
	
	Private _fechaParcial10 As System.Nullable(Of Date)
	
	Private _parcial11 As System.Nullable(Of Integer)
	
	Private _fechaParcial11 As System.Nullable(Of Date)
	
	Private _parcial12 As System.Nullable(Of Integer)
	
	Private _fechaParcial12 As System.Nullable(Of Date)
	
	Private _integrador3 As System.Nullable(Of Integer)
	
	Private _fechaInteg3 As System.Nullable(Of Date)
	
	Private _promedioetapa3 As System.Nullable(Of Decimal)
	
	Private _promedio_anual As System.Nullable(Of Decimal)
	
	Private _coloquio As System.Nullable(Of Integer)
	
	Private _fechacoloquio As System.Nullable(Of Date)
	
	Private _examen As System.Nullable(Of Integer)
	
	Private _fechaexamen As System.Nullable(Of Date)
	
	Private _calif_definitiva As System.Nullable(Of Decimal)
	
	Private _condicion_textbox As String
	
	Private _nombre_materia As String
	
	Private _nombre_alu As String
	
	Private _apellido_alu As String
	
	Private _DNI_alu As Integer
	
	Private _id_alumno As Integer
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_materia", DbType:="Int NOT NULL")>  _
	Public Property id_materia() As Integer
		Get
			Return Me._id_materia
		End Get
		Set
			If ((Me._id_materia = value)  _
						= false) Then
				Me._id_materia = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial1", DbType:="Int")>  _
	Public Property parcial1() As System.Nullable(Of Integer)
		Get
			Return Me._parcial1
		End Get
		Set
			If (Me._parcial1.Equals(value) = false) Then
				Me._parcial1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fechaParcial1", DbType:="Date")>  _
	Public Property fechaParcial1() As System.Nullable(Of Date)
		Get
			Return Me._fechaParcial1
		End Get
		Set
			If (Me._fechaParcial1.Equals(value) = false) Then
				Me._fechaParcial1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial2", DbType:="Int")>  _
	Public Property parcial2() As System.Nullable(Of Integer)
		Get
			Return Me._parcial2
		End Get
		Set
			If (Me._parcial2.Equals(value) = false) Then
				Me._parcial2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fechaParcial2", DbType:="Date")>  _
	Public Property fechaParcial2() As System.Nullable(Of Date)
		Get
			Return Me._fechaParcial2
		End Get
		Set
			If (Me._fechaParcial2.Equals(value) = false) Then
				Me._fechaParcial2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial3", DbType:="Int")>  _
	Public Property parcial3() As System.Nullable(Of Integer)
		Get
			Return Me._parcial3
		End Get
		Set
			If (Me._parcial3.Equals(value) = false) Then
				Me._parcial3 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fechaParcial3", DbType:="Date")>  _
	Public Property fechaParcial3() As System.Nullable(Of Date)
		Get
			Return Me._fechaParcial3
		End Get
		Set
			If (Me._fechaParcial3.Equals(value) = false) Then
				Me._fechaParcial3 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial4", DbType:="Int")>  _
	Public Property parcial4() As System.Nullable(Of Integer)
		Get
			Return Me._parcial4
		End Get
		Set
			If (Me._parcial4.Equals(value) = false) Then
				Me._parcial4 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fechaParcial4", DbType:="Date")>  _
	Public Property fechaParcial4() As System.Nullable(Of Date)
		Get
			Return Me._fechaParcial4
		End Get
		Set
			If (Me._fechaParcial4.Equals(value) = false) Then
				Me._fechaParcial4 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_integrador1", DbType:="Int")>  _
	Public Property integrador1() As System.Nullable(Of Integer)
		Get
			Return Me._integrador1
		End Get
		Set
			If (Me._integrador1.Equals(value) = false) Then
				Me._integrador1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fechaInteg1", DbType:="Date")>  _
	Public Property fechaInteg1() As System.Nullable(Of Date)
		Get
			Return Me._fechaInteg1
		End Get
		Set
			If (Me._fechaInteg1.Equals(value) = false) Then
				Me._fechaInteg1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_promedioetapa1", DbType:="Decimal(4,2)")>  _
	Public Property promedioetapa1() As System.Nullable(Of Decimal)
		Get
			Return Me._promedioetapa1
		End Get
		Set
			If (Me._promedioetapa1.Equals(value) = false) Then
				Me._promedioetapa1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial5", DbType:="Int")>  _
	Public Property parcial5() As System.Nullable(Of Integer)
		Get
			Return Me._parcial5
		End Get
		Set
			If (Me._parcial5.Equals(value) = false) Then
				Me._parcial5 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fechaParcial5", DbType:="Date")>  _
	Public Property fechaParcial5() As System.Nullable(Of Date)
		Get
			Return Me._fechaParcial5
		End Get
		Set
			If (Me._fechaParcial5.Equals(value) = false) Then
				Me._fechaParcial5 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial6", DbType:="Int")>  _
	Public Property parcial6() As System.Nullable(Of Integer)
		Get
			Return Me._parcial6
		End Get
		Set
			If (Me._parcial6.Equals(value) = false) Then
				Me._parcial6 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fechaParcial6", DbType:="Date")>  _
	Public Property fechaParcial6() As System.Nullable(Of Date)
		Get
			Return Me._fechaParcial6
		End Get
		Set
			If (Me._fechaParcial6.Equals(value) = false) Then
				Me._fechaParcial6 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial7", DbType:="Int")>  _
	Public Property parcial7() As System.Nullable(Of Integer)
		Get
			Return Me._parcial7
		End Get
		Set
			If (Me._parcial7.Equals(value) = false) Then
				Me._parcial7 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fechaParcial7", DbType:="Date")>  _
	Public Property fechaParcial7() As System.Nullable(Of Date)
		Get
			Return Me._fechaParcial7
		End Get
		Set
			If (Me._fechaParcial7.Equals(value) = false) Then
				Me._fechaParcial7 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial8", DbType:="Int")>  _
	Public Property parcial8() As System.Nullable(Of Integer)
		Get
			Return Me._parcial8
		End Get
		Set
			If (Me._parcial8.Equals(value) = false) Then
				Me._parcial8 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fechaParcial8", DbType:="Date")>  _
	Public Property fechaParcial8() As System.Nullable(Of Date)
		Get
			Return Me._fechaParcial8
		End Get
		Set
			If (Me._fechaParcial8.Equals(value) = false) Then
				Me._fechaParcial8 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_integrador2", DbType:="Int")>  _
	Public Property integrador2() As System.Nullable(Of Integer)
		Get
			Return Me._integrador2
		End Get
		Set
			If (Me._integrador2.Equals(value) = false) Then
				Me._integrador2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fechaInteg2", DbType:="Date")>  _
	Public Property fechaInteg2() As System.Nullable(Of Date)
		Get
			Return Me._fechaInteg2
		End Get
		Set
			If (Me._fechaInteg2.Equals(value) = false) Then
				Me._fechaInteg2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_promedioetapa2", DbType:="Decimal(4,2)")>  _
	Public Property promedioetapa2() As System.Nullable(Of Decimal)
		Get
			Return Me._promedioetapa2
		End Get
		Set
			If (Me._promedioetapa2.Equals(value) = false) Then
				Me._promedioetapa2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial9", DbType:="Int")>  _
	Public Property parcial9() As System.Nullable(Of Integer)
		Get
			Return Me._parcial9
		End Get
		Set
			If (Me._parcial9.Equals(value) = false) Then
				Me._parcial9 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fechaParcial9", DbType:="Date")>  _
	Public Property fechaParcial9() As System.Nullable(Of Date)
		Get
			Return Me._fechaParcial9
		End Get
		Set
			If (Me._fechaParcial9.Equals(value) = false) Then
				Me._fechaParcial9 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial10", DbType:="Int")>  _
	Public Property parcial10() As System.Nullable(Of Integer)
		Get
			Return Me._parcial10
		End Get
		Set
			If (Me._parcial10.Equals(value) = false) Then
				Me._parcial10 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fechaParcial10", DbType:="Date")>  _
	Public Property fechaParcial10() As System.Nullable(Of Date)
		Get
			Return Me._fechaParcial10
		End Get
		Set
			If (Me._fechaParcial10.Equals(value) = false) Then
				Me._fechaParcial10 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial11", DbType:="Int")>  _
	Public Property parcial11() As System.Nullable(Of Integer)
		Get
			Return Me._parcial11
		End Get
		Set
			If (Me._parcial11.Equals(value) = false) Then
				Me._parcial11 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fechaParcial11", DbType:="Date")>  _
	Public Property fechaParcial11() As System.Nullable(Of Date)
		Get
			Return Me._fechaParcial11
		End Get
		Set
			If (Me._fechaParcial11.Equals(value) = false) Then
				Me._fechaParcial11 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial12", DbType:="Int")>  _
	Public Property parcial12() As System.Nullable(Of Integer)
		Get
			Return Me._parcial12
		End Get
		Set
			If (Me._parcial12.Equals(value) = false) Then
				Me._parcial12 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fechaParcial12", DbType:="Date")>  _
	Public Property fechaParcial12() As System.Nullable(Of Date)
		Get
			Return Me._fechaParcial12
		End Get
		Set
			If (Me._fechaParcial12.Equals(value) = false) Then
				Me._fechaParcial12 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_integrador3", DbType:="Int")>  _
	Public Property integrador3() As System.Nullable(Of Integer)
		Get
			Return Me._integrador3
		End Get
		Set
			If (Me._integrador3.Equals(value) = false) Then
				Me._integrador3 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fechaInteg3", DbType:="Date")>  _
	Public Property fechaInteg3() As System.Nullable(Of Date)
		Get
			Return Me._fechaInteg3
		End Get
		Set
			If (Me._fechaInteg3.Equals(value) = false) Then
				Me._fechaInteg3 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_promedioetapa3", DbType:="Decimal(4,2)")>  _
	Public Property promedioetapa3() As System.Nullable(Of Decimal)
		Get
			Return Me._promedioetapa3
		End Get
		Set
			If (Me._promedioetapa3.Equals(value) = false) Then
				Me._promedioetapa3 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_promedio_anual", DbType:="Decimal(4,2)")>  _
	Public Property promedio_anual() As System.Nullable(Of Decimal)
		Get
			Return Me._promedio_anual
		End Get
		Set
			If (Me._promedio_anual.Equals(value) = false) Then
				Me._promedio_anual = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_coloquio", DbType:="Int")>  _
	Public Property coloquio() As System.Nullable(Of Integer)
		Get
			Return Me._coloquio
		End Get
		Set
			If (Me._coloquio.Equals(value) = false) Then
				Me._coloquio = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fechacoloquio", DbType:="Date")>  _
	Public Property fechacoloquio() As System.Nullable(Of Date)
		Get
			Return Me._fechacoloquio
		End Get
		Set
			If (Me._fechacoloquio.Equals(value) = false) Then
				Me._fechacoloquio = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_examen", DbType:="Int")>  _
	Public Property examen() As System.Nullable(Of Integer)
		Get
			Return Me._examen
		End Get
		Set
			If (Me._examen.Equals(value) = false) Then
				Me._examen = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fechaexamen", DbType:="Date")>  _
	Public Property fechaexamen() As System.Nullable(Of Date)
		Get
			Return Me._fechaexamen
		End Get
		Set
			If (Me._fechaexamen.Equals(value) = false) Then
				Me._fechaexamen = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_calif_definitiva", DbType:="Decimal(4,2)")>  _
	Public Property calif_definitiva() As System.Nullable(Of Decimal)
		Get
			Return Me._calif_definitiva
		End Get
		Set
			If (Me._calif_definitiva.Equals(value) = false) Then
				Me._calif_definitiva = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_condicion_textbox", DbType:="NVarChar(15) NOT NULL", CanBeNull:=false)>  _
	Public Property condicion_textbox() As String
		Get
			Return Me._condicion_textbox
		End Get
		Set
			If (String.Equals(Me._condicion_textbox, value) = false) Then
				Me._condicion_textbox = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_materia", DbType:="NVarChar(40) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_materia() As String
		Get
			Return Me._nombre_materia
		End Get
		Set
			If (String.Equals(Me._nombre_materia, value) = false) Then
				Me._nombre_materia = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_alu", DbType:="VarChar(50)")>  _
	Public Property nombre_alu() As String
		Get
			Return Me._nombre_alu
		End Get
		Set
			If (String.Equals(Me._nombre_alu, value) = false) Then
				Me._nombre_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_apellido_alu", DbType:="VarChar(50)")>  _
	Public Property apellido_alu() As String
		Get
			Return Me._apellido_alu
		End Get
		Set
			If (String.Equals(Me._apellido_alu, value) = false) Then
				Me._apellido_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DNI_alu", DbType:="Int NOT NULL")>  _
	Public Property DNI_alu() As Integer
		Get
			Return Me._DNI_alu
		End Get
		Set
			If ((Me._DNI_alu = value)  _
						= false) Then
				Me._DNI_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_alumno", DbType:="Int NOT NULL")>  _
	Public Property id_alumno() As Integer
		Get
			Return Me._id_alumno
		End Get
		Set
			If ((Me._id_alumno = value)  _
						= false) Then
				Me._id_alumno = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.vista_alum_xcurso")>  _
Partial Public Class vista_alum_xcurso
	
	Private _id_alumno As Integer
	
	Private _nombre_alu As String
	
	Private _apellido_alu As String
	
	Private _DNI_alu As Integer
	
	Private _especialidad As String
	
	Private _nombre_curso As String
	
	Private _turno_textbox As String
	
	Private _fecha_inscripcion_alu As System.Nullable(Of Date)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_alumno", DbType:="Int NOT NULL")>  _
	Public Property id_alumno() As Integer
		Get
			Return Me._id_alumno
		End Get
		Set
			If ((Me._id_alumno = value)  _
						= false) Then
				Me._id_alumno = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_alu", DbType:="VarChar(50)")>  _
	Public Property nombre_alu() As String
		Get
			Return Me._nombre_alu
		End Get
		Set
			If (String.Equals(Me._nombre_alu, value) = false) Then
				Me._nombre_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_apellido_alu", DbType:="VarChar(50)")>  _
	Public Property apellido_alu() As String
		Get
			Return Me._apellido_alu
		End Get
		Set
			If (String.Equals(Me._apellido_alu, value) = false) Then
				Me._apellido_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DNI_alu", DbType:="Int NOT NULL")>  _
	Public Property DNI_alu() As Integer
		Get
			Return Me._DNI_alu
		End Get
		Set
			If ((Me._DNI_alu = value)  _
						= false) Then
				Me._DNI_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_especialidad", DbType:="NVarChar(75) NOT NULL", CanBeNull:=false)>  _
	Public Property especialidad() As String
		Get
			Return Me._especialidad
		End Get
		Set
			If (String.Equals(Me._especialidad, value) = false) Then
				Me._especialidad = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_curso", DbType:="NVarChar(5) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_curso() As String
		Get
			Return Me._nombre_curso
		End Get
		Set
			If (String.Equals(Me._nombre_curso, value) = false) Then
				Me._nombre_curso = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_turno_textbox", DbType:="NVarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property turno_textbox() As String
		Get
			Return Me._turno_textbox
		End Get
		Set
			If (String.Equals(Me._turno_textbox, value) = false) Then
				Me._turno_textbox = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fecha_inscripcion_alu", DbType:="Date")>  _
	Public Property fecha_inscripcion_alu() As System.Nullable(Of Date)
		Get
			Return Me._fecha_inscripcion_alu
		End Get
		Set
			If (Me._fecha_inscripcion_alu.Equals(value) = false) Then
				Me._fecha_inscripcion_alu = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Vista_inasistencia_alumno")>  _
Partial Public Class Vista_inasistencia_alumno
	
	Private _id_asistencia_alu As Integer
	
	Private _fecha_asistencia_alu As Date
	
	Private _observacion_asis_alu As String
	
	Private _estado_asistencia_alu As String
	
	Private _id_alumno As Integer
	
	Private _nombre_alu As String
	
	Private _apellido_alu As String
	
	Private _DNI_alu As Integer
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_asistencia_alu", DbType:="Int NOT NULL")>  _
	Public Property id_asistencia_alu() As Integer
		Get
			Return Me._id_asistencia_alu
		End Get
		Set
			If ((Me._id_asistencia_alu = value)  _
						= false) Then
				Me._id_asistencia_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fecha_asistencia_alu", DbType:="Date NOT NULL")>  _
	Public Property fecha_asistencia_alu() As Date
		Get
			Return Me._fecha_asistencia_alu
		End Get
		Set
			If ((Me._fecha_asistencia_alu = value)  _
						= false) Then
				Me._fecha_asistencia_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_observacion_asis_alu", DbType:="NVarChar(50)")>  _
	Public Property observacion_asis_alu() As String
		Get
			Return Me._observacion_asis_alu
		End Get
		Set
			If (String.Equals(Me._observacion_asis_alu, value) = false) Then
				Me._observacion_asis_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_estado_asistencia_alu", DbType:="NVarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property estado_asistencia_alu() As String
		Get
			Return Me._estado_asistencia_alu
		End Get
		Set
			If (String.Equals(Me._estado_asistencia_alu, value) = false) Then
				Me._estado_asistencia_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_alumno", DbType:="Int NOT NULL")>  _
	Public Property id_alumno() As Integer
		Get
			Return Me._id_alumno
		End Get
		Set
			If ((Me._id_alumno = value)  _
						= false) Then
				Me._id_alumno = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_alu", DbType:="VarChar(50)")>  _
	Public Property nombre_alu() As String
		Get
			Return Me._nombre_alu
		End Get
		Set
			If (String.Equals(Me._nombre_alu, value) = false) Then
				Me._nombre_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_apellido_alu", DbType:="VarChar(50)")>  _
	Public Property apellido_alu() As String
		Get
			Return Me._apellido_alu
		End Get
		Set
			If (String.Equals(Me._apellido_alu, value) = false) Then
				Me._apellido_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DNI_alu", DbType:="Int NOT NULL")>  _
	Public Property DNI_alu() As Integer
		Get
			Return Me._DNI_alu
		End Get
		Set
			If ((Me._DNI_alu = value)  _
						= false) Then
				Me._DNI_alu = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.vista_modulocurso")>  _
Partial Public Class vista_modulocurso
	
	Private _nombre_curso As String
	
	Private _numero As Integer
	
	Private _hora_inicio As System.TimeSpan
	
	Private _hora_fin As System.TimeSpan
	
	Private _id_modulo_x_curso As Integer
	
	Private _turno_textbox As String
	
	Private _id_modulo As Integer
	
	Private _id_curso As Integer
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_curso", DbType:="NVarChar(5) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_curso() As String
		Get
			Return Me._nombre_curso
		End Get
		Set
			If (String.Equals(Me._nombre_curso, value) = false) Then
				Me._nombre_curso = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_numero", DbType:="Int NOT NULL")>  _
	Public Property numero() As Integer
		Get
			Return Me._numero
		End Get
		Set
			If ((Me._numero = value)  _
						= false) Then
				Me._numero = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_hora_inicio", DbType:="Time NOT NULL")>  _
	Public Property hora_inicio() As System.TimeSpan
		Get
			Return Me._hora_inicio
		End Get
		Set
			If ((Me._hora_inicio = value)  _
						= false) Then
				Me._hora_inicio = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_hora_fin", DbType:="Time NOT NULL")>  _
	Public Property hora_fin() As System.TimeSpan
		Get
			Return Me._hora_fin
		End Get
		Set
			If ((Me._hora_fin = value)  _
						= false) Then
				Me._hora_fin = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_modulo_x_curso", DbType:="Int NOT NULL")>  _
	Public Property id_modulo_x_curso() As Integer
		Get
			Return Me._id_modulo_x_curso
		End Get
		Set
			If ((Me._id_modulo_x_curso = value)  _
						= false) Then
				Me._id_modulo_x_curso = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_turno_textbox", DbType:="NVarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property turno_textbox() As String
		Get
			Return Me._turno_textbox
		End Get
		Set
			If (String.Equals(Me._turno_textbox, value) = false) Then
				Me._turno_textbox = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_modulo", DbType:="Int NOT NULL")>  _
	Public Property id_modulo() As Integer
		Get
			Return Me._id_modulo
		End Get
		Set
			If ((Me._id_modulo = value)  _
						= false) Then
				Me._id_modulo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_curso", DbType:="Int NOT NULL")>  _
	Public Property id_curso() As Integer
		Get
			Return Me._id_curso
		End Get
		Set
			If ((Me._id_curso = value)  _
						= false) Then
				Me._id_curso = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.VistaProfxMateria")>  _
Partial Public Class VistaProfxMateria
	
	Private _cant_hs_catedra As Integer
	
	Private _id_profesor_materia As Integer
	
	Private _id_curso As Integer
	
	Private _nombre_curso As String
	
	Private _nombre_materia As String
	
	Private _id_personal As Integer
	
	Private _id_materia As Integer
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cant_hs_catedra", DbType:="Int NOT NULL")>  _
	Public Property cant_hs_catedra() As Integer
		Get
			Return Me._cant_hs_catedra
		End Get
		Set
			If ((Me._cant_hs_catedra = value)  _
						= false) Then
				Me._cant_hs_catedra = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_profesor_materia", DbType:="Int NOT NULL")>  _
	Public Property id_profesor_materia() As Integer
		Get
			Return Me._id_profesor_materia
		End Get
		Set
			If ((Me._id_profesor_materia = value)  _
						= false) Then
				Me._id_profesor_materia = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_curso", DbType:="Int NOT NULL")>  _
	Public Property id_curso() As Integer
		Get
			Return Me._id_curso
		End Get
		Set
			If ((Me._id_curso = value)  _
						= false) Then
				Me._id_curso = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_curso", DbType:="NVarChar(5) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_curso() As String
		Get
			Return Me._nombre_curso
		End Get
		Set
			If (String.Equals(Me._nombre_curso, value) = false) Then
				Me._nombre_curso = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_materia", DbType:="NVarChar(40) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_materia() As String
		Get
			Return Me._nombre_materia
		End Get
		Set
			If (String.Equals(Me._nombre_materia, value) = false) Then
				Me._nombre_materia = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_personal", DbType:="Int NOT NULL")>  _
	Public Property id_personal() As Integer
		Get
			Return Me._id_personal
		End Get
		Set
			If ((Me._id_personal = value)  _
						= false) Then
				Me._id_personal = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_materia", DbType:="Int NOT NULL")>  _
	Public Property id_materia() As Integer
		Get
			Return Me._id_materia
		End Get
		Set
			If ((Me._id_materia = value)  _
						= false) Then
				Me._id_materia = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.VistaEstCalifxAlu")>  _
Partial Public Class VistaEstCalifxAlu
	
	Private _id_alumno As Integer
	
	Private _Total As System.Nullable(Of Integer)
	
	Private _nombre_curso As String
	
	Private _id_curso As Integer
	
	Private _condicion_textbox As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_alumno", DbType:="Int NOT NULL")>  _
	Public Property id_alumno() As Integer
		Get
			Return Me._id_alumno
		End Get
		Set
			If ((Me._id_alumno = value)  _
						= false) Then
				Me._id_alumno = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Total", DbType:="Int")>  _
	Public Property Total() As System.Nullable(Of Integer)
		Get
			Return Me._Total
		End Get
		Set
			If (Me._Total.Equals(value) = false) Then
				Me._Total = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_curso", DbType:="NVarChar(5) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_curso() As String
		Get
			Return Me._nombre_curso
		End Get
		Set
			If (String.Equals(Me._nombre_curso, value) = false) Then
				Me._nombre_curso = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_curso", DbType:="Int NOT NULL")>  _
	Public Property id_curso() As Integer
		Get
			Return Me._id_curso
		End Get
		Set
			If ((Me._id_curso = value)  _
						= false) Then
				Me._id_curso = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_condicion_textbox", DbType:="NVarChar(15) NOT NULL", CanBeNull:=false)>  _
	Public Property condicion_textbox() As String
		Get
			Return Me._condicion_textbox
		End Get
		Set
			If (String.Equals(Me._condicion_textbox, value) = false) Then
				Me._condicion_textbox = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.VistaCalifxCurso")>  _
Partial Public Class VistaCalifxCurso
	
	Private _id_alumno As Integer
	
	Private _id_curso As Integer
	
	Private _nombre_curso As String
	
	Private _calif_definitiva As System.Nullable(Of Decimal)
	
	Private _Total As System.Nullable(Of Integer)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_alumno", DbType:="Int NOT NULL")>  _
	Public Property id_alumno() As Integer
		Get
			Return Me._id_alumno
		End Get
		Set
			If ((Me._id_alumno = value)  _
						= false) Then
				Me._id_alumno = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_curso", DbType:="Int NOT NULL")>  _
	Public Property id_curso() As Integer
		Get
			Return Me._id_curso
		End Get
		Set
			If ((Me._id_curso = value)  _
						= false) Then
				Me._id_curso = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_curso", DbType:="NVarChar(5) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_curso() As String
		Get
			Return Me._nombre_curso
		End Get
		Set
			If (String.Equals(Me._nombre_curso, value) = false) Then
				Me._nombre_curso = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_calif_definitiva", DbType:="Decimal(4,2)")>  _
	Public Property calif_definitiva() As System.Nullable(Of Decimal)
		Get
			Return Me._calif_definitiva
		End Get
		Set
			If (Me._calif_definitiva.Equals(value) = false) Then
				Me._calif_definitiva = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Total", DbType:="Int")>  _
	Public Property Total() As System.Nullable(Of Integer)
		Get
			Return Me._Total
		End Get
		Set
			If (Me._Total.Equals(value) = false) Then
				Me._Total = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.VistaPrueba")>  _
Partial Public Class VistaPrueba
	
	Private _id_alumno As Integer
	
	Private _Total As System.Nullable(Of Integer)
	
	Private _id_materia As Integer
	
	Private _nombre_materia As String
	
	Private _condicion_textbox As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_alumno", DbType:="Int NOT NULL")>  _
	Public Property id_alumno() As Integer
		Get
			Return Me._id_alumno
		End Get
		Set
			If ((Me._id_alumno = value)  _
						= false) Then
				Me._id_alumno = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Total", DbType:="Int")>  _
	Public Property Total() As System.Nullable(Of Integer)
		Get
			Return Me._Total
		End Get
		Set
			If (Me._Total.Equals(value) = false) Then
				Me._Total = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_materia", DbType:="Int NOT NULL")>  _
	Public Property id_materia() As Integer
		Get
			Return Me._id_materia
		End Get
		Set
			If ((Me._id_materia = value)  _
						= false) Then
				Me._id_materia = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_materia", DbType:="NVarChar(40) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_materia() As String
		Get
			Return Me._nombre_materia
		End Get
		Set
			If (String.Equals(Me._nombre_materia, value) = false) Then
				Me._nombre_materia = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_condicion_textbox", DbType:="NVarChar(15) NOT NULL", CanBeNull:=false)>  _
	Public Property condicion_textbox() As String
		Get
			Return Me._condicion_textbox
		End Get
		Set
			If (String.Equals(Me._condicion_textbox, value) = false) Then
				Me._condicion_textbox = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.vista_horario_personal")>  _
Partial Public Class vista_horario_personal
	
	Private _dia_semana As String
	
	Private _nombre_materia As String
	
	Private _nombre_curso As String
	
	Private _numero As Integer
	
	Private _hora_inicio As System.TimeSpan
	
	Private _hora_fin As System.TimeSpan
	
	Private _id_horario As Integer
	
	Private _id_personal As Integer
	
	Private _turno_textbox As String
	
	Private _especialidad_textbox As String
	
	Private _nombre_pers As String
	
	Private _apelliido_pers As String
	
	Private _inicio As String
	
	Private _final As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dia_semana", DbType:="VarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property dia_semana() As String
		Get
			Return Me._dia_semana
		End Get
		Set
			If (String.Equals(Me._dia_semana, value) = false) Then
				Me._dia_semana = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_materia", DbType:="NVarChar(40) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_materia() As String
		Get
			Return Me._nombre_materia
		End Get
		Set
			If (String.Equals(Me._nombre_materia, value) = false) Then
				Me._nombre_materia = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_curso", DbType:="NVarChar(5) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_curso() As String
		Get
			Return Me._nombre_curso
		End Get
		Set
			If (String.Equals(Me._nombre_curso, value) = false) Then
				Me._nombre_curso = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_numero", DbType:="Int NOT NULL")>  _
	Public Property numero() As Integer
		Get
			Return Me._numero
		End Get
		Set
			If ((Me._numero = value)  _
						= false) Then
				Me._numero = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_hora_inicio", DbType:="Time NOT NULL")>  _
	Public Property hora_inicio() As System.TimeSpan
		Get
			Return Me._hora_inicio
		End Get
		Set
			If ((Me._hora_inicio = value)  _
						= false) Then
				Me._hora_inicio = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_hora_fin", DbType:="Time NOT NULL")>  _
	Public Property hora_fin() As System.TimeSpan
		Get
			Return Me._hora_fin
		End Get
		Set
			If ((Me._hora_fin = value)  _
						= false) Then
				Me._hora_fin = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_horario", DbType:="Int NOT NULL")>  _
	Public Property id_horario() As Integer
		Get
			Return Me._id_horario
		End Get
		Set
			If ((Me._id_horario = value)  _
						= false) Then
				Me._id_horario = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_personal", DbType:="Int NOT NULL")>  _
	Public Property id_personal() As Integer
		Get
			Return Me._id_personal
		End Get
		Set
			If ((Me._id_personal = value)  _
						= false) Then
				Me._id_personal = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_turno_textbox", DbType:="NVarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property turno_textbox() As String
		Get
			Return Me._turno_textbox
		End Get
		Set
			If (String.Equals(Me._turno_textbox, value) = false) Then
				Me._turno_textbox = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_especialidad_textbox", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property especialidad_textbox() As String
		Get
			Return Me._especialidad_textbox
		End Get
		Set
			If (String.Equals(Me._especialidad_textbox, value) = false) Then
				Me._especialidad_textbox = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_pers", DbType:="NVarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_pers() As String
		Get
			Return Me._nombre_pers
		End Get
		Set
			If (String.Equals(Me._nombre_pers, value) = false) Then
				Me._nombre_pers = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_apelliido_pers", DbType:="NVarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property apelliido_pers() As String
		Get
			Return Me._apelliido_pers
		End Get
		Set
			If (String.Equals(Me._apelliido_pers, value) = false) Then
				Me._apelliido_pers = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_inicio", DbType:="Char(10)")>  _
	Public Property inicio() As String
		Get
			Return Me._inicio
		End Get
		Set
			If (String.Equals(Me._inicio, value) = false) Then
				Me._inicio = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_final", DbType:="Char(10)")>  _
	Public Property final() As String
		Get
			Return Me._final
		End Get
		Set
			If (String.Equals(Me._final, value) = false) Then
				Me._final = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Vista_libreta")>  _
Partial Public Class Vista_libreta
	
	Private _id_materia As Integer
	
	Private _parcial1 As System.Nullable(Of Integer)
	
	Private _parcial2 As System.Nullable(Of Integer)
	
	Private _parcial3 As System.Nullable(Of Integer)
	
	Private _parcial4 As System.Nullable(Of Integer)
	
	Private _integrador1 As System.Nullable(Of Integer)
	
	Private _promedioetapa1 As System.Nullable(Of Decimal)
	
	Private _parcial5 As System.Nullable(Of Integer)
	
	Private _parcial6 As System.Nullable(Of Integer)
	
	Private _parcial7 As System.Nullable(Of Integer)
	
	Private _parcial8 As System.Nullable(Of Integer)
	
	Private _integrador2 As System.Nullable(Of Integer)
	
	Private _promedioetapa2 As System.Nullable(Of Decimal)
	
	Private _parcial9 As System.Nullable(Of Integer)
	
	Private _parcial10 As System.Nullable(Of Integer)
	
	Private _parcial11 As System.Nullable(Of Integer)
	
	Private _parcial12 As System.Nullable(Of Integer)
	
	Private _integrador3 As System.Nullable(Of Integer)
	
	Private _promedioetapa3 As System.Nullable(Of Decimal)
	
	Private _promedio_anual As System.Nullable(Of Decimal)
	
	Private _coloquio As System.Nullable(Of Integer)
	
	Private _examen As System.Nullable(Of Integer)
	
	Private _calif_definitiva As System.Nullable(Of Decimal)
	
	Private _condicion_textbox As String
	
	Private _nombre_materia As String
	
	Private _nombre_alu As String
	
	Private _apellido_alu As String
	
	Private _DNI_alu As Integer
	
	Private _id_alumno As Integer
	
	Private _nombre_curso As String
	
	Private _turno_textbox As String
	
	Private _especialidad As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_materia", DbType:="Int NOT NULL")>  _
	Public Property id_materia() As Integer
		Get
			Return Me._id_materia
		End Get
		Set
			If ((Me._id_materia = value)  _
						= false) Then
				Me._id_materia = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial1", DbType:="Int")>  _
	Public Property parcial1() As System.Nullable(Of Integer)
		Get
			Return Me._parcial1
		End Get
		Set
			If (Me._parcial1.Equals(value) = false) Then
				Me._parcial1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial2", DbType:="Int")>  _
	Public Property parcial2() As System.Nullable(Of Integer)
		Get
			Return Me._parcial2
		End Get
		Set
			If (Me._parcial2.Equals(value) = false) Then
				Me._parcial2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial3", DbType:="Int")>  _
	Public Property parcial3() As System.Nullable(Of Integer)
		Get
			Return Me._parcial3
		End Get
		Set
			If (Me._parcial3.Equals(value) = false) Then
				Me._parcial3 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial4", DbType:="Int")>  _
	Public Property parcial4() As System.Nullable(Of Integer)
		Get
			Return Me._parcial4
		End Get
		Set
			If (Me._parcial4.Equals(value) = false) Then
				Me._parcial4 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_integrador1", DbType:="Int")>  _
	Public Property integrador1() As System.Nullable(Of Integer)
		Get
			Return Me._integrador1
		End Get
		Set
			If (Me._integrador1.Equals(value) = false) Then
				Me._integrador1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_promedioetapa1", DbType:="Decimal(4,2)")>  _
	Public Property promedioetapa1() As System.Nullable(Of Decimal)
		Get
			Return Me._promedioetapa1
		End Get
		Set
			If (Me._promedioetapa1.Equals(value) = false) Then
				Me._promedioetapa1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial5", DbType:="Int")>  _
	Public Property parcial5() As System.Nullable(Of Integer)
		Get
			Return Me._parcial5
		End Get
		Set
			If (Me._parcial5.Equals(value) = false) Then
				Me._parcial5 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial6", DbType:="Int")>  _
	Public Property parcial6() As System.Nullable(Of Integer)
		Get
			Return Me._parcial6
		End Get
		Set
			If (Me._parcial6.Equals(value) = false) Then
				Me._parcial6 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial7", DbType:="Int")>  _
	Public Property parcial7() As System.Nullable(Of Integer)
		Get
			Return Me._parcial7
		End Get
		Set
			If (Me._parcial7.Equals(value) = false) Then
				Me._parcial7 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial8", DbType:="Int")>  _
	Public Property parcial8() As System.Nullable(Of Integer)
		Get
			Return Me._parcial8
		End Get
		Set
			If (Me._parcial8.Equals(value) = false) Then
				Me._parcial8 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_integrador2", DbType:="Int")>  _
	Public Property integrador2() As System.Nullable(Of Integer)
		Get
			Return Me._integrador2
		End Get
		Set
			If (Me._integrador2.Equals(value) = false) Then
				Me._integrador2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_promedioetapa2", DbType:="Decimal(4,2)")>  _
	Public Property promedioetapa2() As System.Nullable(Of Decimal)
		Get
			Return Me._promedioetapa2
		End Get
		Set
			If (Me._promedioetapa2.Equals(value) = false) Then
				Me._promedioetapa2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial9", DbType:="Int")>  _
	Public Property parcial9() As System.Nullable(Of Integer)
		Get
			Return Me._parcial9
		End Get
		Set
			If (Me._parcial9.Equals(value) = false) Then
				Me._parcial9 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial10", DbType:="Int")>  _
	Public Property parcial10() As System.Nullable(Of Integer)
		Get
			Return Me._parcial10
		End Get
		Set
			If (Me._parcial10.Equals(value) = false) Then
				Me._parcial10 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial11", DbType:="Int")>  _
	Public Property parcial11() As System.Nullable(Of Integer)
		Get
			Return Me._parcial11
		End Get
		Set
			If (Me._parcial11.Equals(value) = false) Then
				Me._parcial11 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_parcial12", DbType:="Int")>  _
	Public Property parcial12() As System.Nullable(Of Integer)
		Get
			Return Me._parcial12
		End Get
		Set
			If (Me._parcial12.Equals(value) = false) Then
				Me._parcial12 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_integrador3", DbType:="Int")>  _
	Public Property integrador3() As System.Nullable(Of Integer)
		Get
			Return Me._integrador3
		End Get
		Set
			If (Me._integrador3.Equals(value) = false) Then
				Me._integrador3 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_promedioetapa3", DbType:="Decimal(4,2)")>  _
	Public Property promedioetapa3() As System.Nullable(Of Decimal)
		Get
			Return Me._promedioetapa3
		End Get
		Set
			If (Me._promedioetapa3.Equals(value) = false) Then
				Me._promedioetapa3 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_promedio_anual", DbType:="Decimal(4,2)")>  _
	Public Property promedio_anual() As System.Nullable(Of Decimal)
		Get
			Return Me._promedio_anual
		End Get
		Set
			If (Me._promedio_anual.Equals(value) = false) Then
				Me._promedio_anual = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_coloquio", DbType:="Int")>  _
	Public Property coloquio() As System.Nullable(Of Integer)
		Get
			Return Me._coloquio
		End Get
		Set
			If (Me._coloquio.Equals(value) = false) Then
				Me._coloquio = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_examen", DbType:="Int")>  _
	Public Property examen() As System.Nullable(Of Integer)
		Get
			Return Me._examen
		End Get
		Set
			If (Me._examen.Equals(value) = false) Then
				Me._examen = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_calif_definitiva", DbType:="Decimal(4,2)")>  _
	Public Property calif_definitiva() As System.Nullable(Of Decimal)
		Get
			Return Me._calif_definitiva
		End Get
		Set
			If (Me._calif_definitiva.Equals(value) = false) Then
				Me._calif_definitiva = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_condicion_textbox", DbType:="NVarChar(15)")>  _
	Public Property condicion_textbox() As String
		Get
			Return Me._condicion_textbox
		End Get
		Set
			If (String.Equals(Me._condicion_textbox, value) = false) Then
				Me._condicion_textbox = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_materia", DbType:="NVarChar(40) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_materia() As String
		Get
			Return Me._nombre_materia
		End Get
		Set
			If (String.Equals(Me._nombre_materia, value) = false) Then
				Me._nombre_materia = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_alu", DbType:="VarChar(50)")>  _
	Public Property nombre_alu() As String
		Get
			Return Me._nombre_alu
		End Get
		Set
			If (String.Equals(Me._nombre_alu, value) = false) Then
				Me._nombre_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_apellido_alu", DbType:="VarChar(50)")>  _
	Public Property apellido_alu() As String
		Get
			Return Me._apellido_alu
		End Get
		Set
			If (String.Equals(Me._apellido_alu, value) = false) Then
				Me._apellido_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DNI_alu", DbType:="Int NOT NULL")>  _
	Public Property DNI_alu() As Integer
		Get
			Return Me._DNI_alu
		End Get
		Set
			If ((Me._DNI_alu = value)  _
						= false) Then
				Me._DNI_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_alumno", DbType:="Int NOT NULL")>  _
	Public Property id_alumno() As Integer
		Get
			Return Me._id_alumno
		End Get
		Set
			If ((Me._id_alumno = value)  _
						= false) Then
				Me._id_alumno = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_curso", DbType:="NVarChar(5) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_curso() As String
		Get
			Return Me._nombre_curso
		End Get
		Set
			If (String.Equals(Me._nombre_curso, value) = false) Then
				Me._nombre_curso = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_turno_textbox", DbType:="NVarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property turno_textbox() As String
		Get
			Return Me._turno_textbox
		End Get
		Set
			If (String.Equals(Me._turno_textbox, value) = false) Then
				Me._turno_textbox = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_especialidad", DbType:="NVarChar(75) NOT NULL", CanBeNull:=false)>  _
	Public Property especialidad() As String
		Get
			Return Me._especialidad
		End Get
		Set
			If (String.Equals(Me._especialidad, value) = false) Then
				Me._especialidad = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Vista_profesor_x_materia")>  _
Partial Public Class Vista_profesor_x_materia
	
	Private _id_profesor_materia As Integer
	
	Private _apelliido_pers As String
	
	Private _nombre_pers As String
	
	Private _DNI_pers As Integer
	
	Private _nombre_materia As String
	
	Private _nombre_curso As String
	
	Private _puesto_pers As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_profesor_materia", DbType:="Int NOT NULL")>  _
	Public Property id_profesor_materia() As Integer
		Get
			Return Me._id_profesor_materia
		End Get
		Set
			If ((Me._id_profesor_materia = value)  _
						= false) Then
				Me._id_profesor_materia = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_apelliido_pers", DbType:="NVarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property apelliido_pers() As String
		Get
			Return Me._apelliido_pers
		End Get
		Set
			If (String.Equals(Me._apelliido_pers, value) = false) Then
				Me._apelliido_pers = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_pers", DbType:="NVarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_pers() As String
		Get
			Return Me._nombre_pers
		End Get
		Set
			If (String.Equals(Me._nombre_pers, value) = false) Then
				Me._nombre_pers = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DNI_pers", DbType:="Int NOT NULL")>  _
	Public Property DNI_pers() As Integer
		Get
			Return Me._DNI_pers
		End Get
		Set
			If ((Me._DNI_pers = value)  _
						= false) Then
				Me._DNI_pers = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_materia", DbType:="NVarChar(40) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_materia() As String
		Get
			Return Me._nombre_materia
		End Get
		Set
			If (String.Equals(Me._nombre_materia, value) = false) Then
				Me._nombre_materia = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_curso", DbType:="NVarChar(5) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_curso() As String
		Get
			Return Me._nombre_curso
		End Get
		Set
			If (String.Equals(Me._nombre_curso, value) = false) Then
				Me._nombre_curso = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_puesto_pers", DbType:="NVarChar(50)")>  _
	Public Property puesto_pers() As String
		Get
			Return Me._puesto_pers
		End Get
		Set
			If (String.Equals(Me._puesto_pers, value) = false) Then
				Me._puesto_pers = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Vista_Alumno2")>  _
Partial Public Class Vista_Alumno2
	
	Private _id_alumno_x_curso As Integer
	
	Private _id_alumno As Integer
	
	Private _id_curso As Integer
	
	Private _especialidad As String
	
	Private _Expr1 As Integer
	
	Private _Expr4 As String
	
	Private _nombre_alu As String
	
	Private _apellido_alu As String
	
	Private _DNI_alu As Integer
	
	Private _nombre_curso As String
	
	Private _Expr3 As Integer
	
	Private _Expr6 As Integer
	
	Private _fecha_inscripcion_alu As System.Nullable(Of Date)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_alumno_x_curso", DbType:="Int NOT NULL")>  _
	Public Property id_alumno_x_curso() As Integer
		Get
			Return Me._id_alumno_x_curso
		End Get
		Set
			If ((Me._id_alumno_x_curso = value)  _
						= false) Then
				Me._id_alumno_x_curso = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_alumno", DbType:="Int NOT NULL")>  _
	Public Property id_alumno() As Integer
		Get
			Return Me._id_alumno
		End Get
		Set
			If ((Me._id_alumno = value)  _
						= false) Then
				Me._id_alumno = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_curso", DbType:="Int NOT NULL")>  _
	Public Property id_curso() As Integer
		Get
			Return Me._id_curso
		End Get
		Set
			If ((Me._id_curso = value)  _
						= false) Then
				Me._id_curso = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_especialidad", DbType:="NVarChar(75) NOT NULL", CanBeNull:=false)>  _
	Public Property especialidad() As String
		Get
			Return Me._especialidad
		End Get
		Set
			If (String.Equals(Me._especialidad, value) = false) Then
				Me._especialidad = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Expr1", DbType:="Int NOT NULL")>  _
	Public Property Expr1() As Integer
		Get
			Return Me._Expr1
		End Get
		Set
			If ((Me._Expr1 = value)  _
						= false) Then
				Me._Expr1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Expr4", DbType:="NVarChar(75) NOT NULL", CanBeNull:=false)>  _
	Public Property Expr4() As String
		Get
			Return Me._Expr4
		End Get
		Set
			If (String.Equals(Me._Expr4, value) = false) Then
				Me._Expr4 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_alu", DbType:="VarChar(50)")>  _
	Public Property nombre_alu() As String
		Get
			Return Me._nombre_alu
		End Get
		Set
			If (String.Equals(Me._nombre_alu, value) = false) Then
				Me._nombre_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_apellido_alu", DbType:="VarChar(50)")>  _
	Public Property apellido_alu() As String
		Get
			Return Me._apellido_alu
		End Get
		Set
			If (String.Equals(Me._apellido_alu, value) = false) Then
				Me._apellido_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DNI_alu", DbType:="Int NOT NULL")>  _
	Public Property DNI_alu() As Integer
		Get
			Return Me._DNI_alu
		End Get
		Set
			If ((Me._DNI_alu = value)  _
						= false) Then
				Me._DNI_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_curso", DbType:="NVarChar(5) NOT NULL", CanBeNull:=false)>  _
	Public Property nombre_curso() As String
		Get
			Return Me._nombre_curso
		End Get
		Set
			If (String.Equals(Me._nombre_curso, value) = false) Then
				Me._nombre_curso = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Expr3", DbType:="Int NOT NULL")>  _
	Public Property Expr3() As Integer
		Get
			Return Me._Expr3
		End Get
		Set
			If ((Me._Expr3 = value)  _
						= false) Then
				Me._Expr3 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Expr6", DbType:="Int NOT NULL")>  _
	Public Property Expr6() As Integer
		Get
			Return Me._Expr6
		End Get
		Set
			If ((Me._Expr6 = value)  _
						= false) Then
				Me._Expr6 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fecha_inscripcion_alu", DbType:="Date")>  _
	Public Property fecha_inscripcion_alu() As System.Nullable(Of Date)
		Get
			Return Me._fecha_inscripcion_alu
		End Get
		Set
			If (Me._fecha_inscripcion_alu.Equals(value) = false) Then
				Me._fecha_inscripcion_alu = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Vista_alumnos_no_asignados_curso")>  _
Partial Public Class Vista_alumnos_no_asignados_curso
	
	Private _id_alumno As Integer
	
	Private _nombre_alu As String
	
	Private _apellido_alu As String
	
	Private _domicilio As String
	
	Private _DNI_alu As Integer
	
	Private _fecha_inscripcion_alu As System.Nullable(Of Date)
	
	Private _fecha_nac_alu As System.Nullable(Of Date)
	
	Private _mail_alu As String
	
	Private _nomb_ape_tutor As String
	
	Private _dni_tutor As System.Nullable(Of Integer)
	
	Private _telefono_tutor As String
	
	Private _foto_alu As System.Data.Linq.Binary
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_alumno", AutoSync:=AutoSync.Always, DbType:="Int NOT NULL IDENTITY", IsDbGenerated:=true)>  _
	Public Property id_alumno() As Integer
		Get
			Return Me._id_alumno
		End Get
		Set
			If ((Me._id_alumno = value)  _
						= false) Then
				Me._id_alumno = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre_alu", DbType:="VarChar(50)")>  _
	Public Property nombre_alu() As String
		Get
			Return Me._nombre_alu
		End Get
		Set
			If (String.Equals(Me._nombre_alu, value) = false) Then
				Me._nombre_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_apellido_alu", DbType:="VarChar(50)")>  _
	Public Property apellido_alu() As String
		Get
			Return Me._apellido_alu
		End Get
		Set
			If (String.Equals(Me._apellido_alu, value) = false) Then
				Me._apellido_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_domicilio", DbType:="VarChar(50)")>  _
	Public Property domicilio() As String
		Get
			Return Me._domicilio
		End Get
		Set
			If (String.Equals(Me._domicilio, value) = false) Then
				Me._domicilio = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DNI_alu", DbType:="Int NOT NULL")>  _
	Public Property DNI_alu() As Integer
		Get
			Return Me._DNI_alu
		End Get
		Set
			If ((Me._DNI_alu = value)  _
						= false) Then
				Me._DNI_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fecha_inscripcion_alu", DbType:="Date")>  _
	Public Property fecha_inscripcion_alu() As System.Nullable(Of Date)
		Get
			Return Me._fecha_inscripcion_alu
		End Get
		Set
			If (Me._fecha_inscripcion_alu.Equals(value) = false) Then
				Me._fecha_inscripcion_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fecha_nac_alu", DbType:="Date")>  _
	Public Property fecha_nac_alu() As System.Nullable(Of Date)
		Get
			Return Me._fecha_nac_alu
		End Get
		Set
			If (Me._fecha_nac_alu.Equals(value) = false) Then
				Me._fecha_nac_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_mail_alu", DbType:="VarChar(50)")>  _
	Public Property mail_alu() As String
		Get
			Return Me._mail_alu
		End Get
		Set
			If (String.Equals(Me._mail_alu, value) = false) Then
				Me._mail_alu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nomb_ape_tutor", DbType:="VarChar(50)")>  _
	Public Property nomb_ape_tutor() As String
		Get
			Return Me._nomb_ape_tutor
		End Get
		Set
			If (String.Equals(Me._nomb_ape_tutor, value) = false) Then
				Me._nomb_ape_tutor = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dni_tutor", DbType:="Int")>  _
	Public Property dni_tutor() As System.Nullable(Of Integer)
		Get
			Return Me._dni_tutor
		End Get
		Set
			If (Me._dni_tutor.Equals(value) = false) Then
				Me._dni_tutor = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_telefono_tutor", DbType:="VarChar(20)")>  _
	Public Property telefono_tutor() As String
		Get
			Return Me._telefono_tutor
		End Get
		Set
			If (String.Equals(Me._telefono_tutor, value) = false) Then
				Me._telefono_tutor = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_foto_alu", DbType:="Image", CanBeNull:=true, UpdateCheck:=UpdateCheck.Never)>  _
	Public Property foto_alu() As System.Data.Linq.Binary
		Get
			Return Me._foto_alu
		End Get
		Set
			If (Object.Equals(Me._foto_alu, value) = false) Then
				Me._foto_alu = value
			End If
		End Set
	End Property
End Class
